replicaCount: 1

image:
  repository: ghcr.io/robokopu24/landing-page
  tag: v2.0.11

# NEXT_PUBLIC_RECAPTCHA_KEY is provided in .env.production file
# env:

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 3000

# Check for override in parent chart
ingress:
  host: test-rkfe.apps.renci.org
  path: /(.*)$
  tls: true
  public: false
