replicaCount: 1

image:
  repository: ghcr.io/robokopu24/robokopu24.github.io
  tag: latest

# NEXT_PUBLIC_RECAPTCHA_KEY is provided in .env.production file
# env:

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 3000
