dataUrl: https://stars.renci.org/var/plater/bl-3.4.2/YobokopKG/bdd116c0308604f3/graph_bdd116c0308604f3.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-3.4.2/YobokopKG/bdd116c0308604f3/YobokopKG.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-3.4.2/YobokopKG/bdd116c0308604f3/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-3.4.2/YobokopKG/bdd116c0308604f3/testing_data.json