dataUrl: https://stars.renci.org/var/plater/bl-4.2.0/YobokopKG/40614106c036f010/graph_40614106c036f010.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-4.2.0/YobokopKG/40614106c036f010/YobokopKG.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-4.2.0/YobokopKG/40614106c036f010/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-4.2.0/YobokopKG/40614106c036f010/testing_data.json