apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "translator-workflow-runner.fullname" . }}
  labels:
    app: {{ include "translator-workflow-runner.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "translator-workflow-runner.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "translator-workflow-runner.name" . }}
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: {{ include "translator-workflow-runner.fullname" . }}-configmap
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: {{ .Chart.Name }}-web-container
          env:
          {{ if .Values.HTTPS_PROXY }}
            - name: "HTTPS_PROXY"
              value: "{{ .Values.HTTPS_PROXY }}"
            {{ end }}
          {{ if .Values.NO_PROXY }}
            - name: "NO_PROXY"
              value: "{{ .Values.NO_PROXY}}"
          {{ end }}
          ports:
          - containerPort: {{ .Values.app.port }}
            name: http
            protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
