apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "openapi-spec-aggregator.fullname" . }}-update-cron
spec:
  schedule: {{ .Values.refreshInterval }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: refresh
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - wget
            - http://{{ include "openapi-spec-aggregator.fullname" . }}:{{ .Values.service.port }}/refresh            
          restartPolicy: OnFailure