{{- $open_api_config := toYaml .Values.app.openapi_config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plater.fullname" . }}-configmap
  labels:
    {{- include "plater.labels" . | nindent 4 }}
data:
  check_neo.sh: |-
    #!/bin/sh
    response=$(wget --server-response --spider --quiet "http://${NEO4J_HOST}:${NEO4J_HTTP_PORT}" 2>&1 | awk 'NR==1{print $2}')
    until [ "$response" = "200" ]; do
        response=$(wget --server-response --spider --quiet "http://${NEO4J_HOST}:${NEO4J_HTTP_PORT}" 2>&1 | awk 'NR==1{print $2}') >&2
        echo "  -- Neo4j  is unavailable - sleeping"
        sleep 3
    done
  download_data.sh: |-
    #!/bin/bash
    set -x
    wget -O /data/neo4j.dump ${NEO4J_DATA_URL}
    touch /data/done
  download_metadata.sh: |-
    #!/bin/sh
    set -x
    if [[ "${PLATER_METADATA_URL}" ]]
    then
        wget -O /home/plater/Plater/PLATER/metadata/metadata.json "${PLATER_METADATA_URL}"
    fi
    if [[ "${PLATER_METAKG_URL}" ]]
    then
        wget -O /home/plater/Plater/PLATER/metadata/meta_knowledge_graph.json "${PLATER_METAKG_URL}"
    fi
    if [[ "${PLATER_TEST_DATA_URL}" ]]
    then
        wget -O /home/plater/Plater/PLATER/metadata/sri_testing_data.json "${PLATER_TEST_DATA_URL}"
    fi
  seed_db.sh: |-
    #!/bin/bash
    set -x
    FILE=/data/neo4j.dump
    DATADIR=/data/databases
    until [ -f "$FILE" ]; do
        echo "$FILE doesn't exist. Please copy to database dump file to $FILE"
        echo "sleeping..."
        sleep 3
    done
    echo "$FILE found"
    echo "clearing previous database file if any..."
    # Make dir if they don't exist
    mkdir -p /data/databases
    mkdir -p /data/transactions
    mkdir -p /data/dbms
    # clear out data from dir if they were present
    rm -rf /data/dbms/*
    rm -rf /data/databases/*
    rm -rf /data/transactions/*
    # load dump file
    neo4j-admin database load --from-path=/data neo4j
  dataset-desc.json: |
    {{ .Values.datasetDesc | toJson }}
  openapi-config.yaml: |-
{{ tpl $open_api_config . | indent 4 }}
  skip-attr.json: |
    {{ .Values.skipAttributes | toJson }}