apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plater.fullname" . }}-web
  labels:
    {{- include "plater.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "plater.selectorLabels" . | nindent 6 }}
      service-type: web-server
  template:
    metadata:
      labels:
        {{- include "plater.selectorLabels" . | nindent 8 }}
        service-type: web-server
      annotations:
        checksum/openapi: {{ print .Values.app.openapi_config | sha256sum }}
        checksum/envconfig: {{ include (print $.Template.BasePath "/env-config-map.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: {{ include "plater.fullname" . }}-metadata-download-container
          image: "{{ .Values.bash.image.repository }}:{{ .Values.bash.image.tag }}"
          command:
            - './download_metadata.sh'
          envFrom:
            - configMapRef:
                name: {{ include "plater.fullname" . }}-env-configmap
          volumeMounts:
            - name: {{ include "plater.fullname" . }}-config-files
              mountPath: /download_metadata.sh
              subPath: download_metadata.sh
            - name: {{ include "plater.fullname" . }}-metadata-pvc
              mountPath: /home/plater/Plater/PLATER/metadata
              subPath: plater-metadata/
        - name: {{ include "plater.fullname" . }}-init-container
          image: "{{ .Values.busybox.image.repository }}:{{ .Values.busybox.image.tag }}"
          command:
            - './check_neo.sh'
          env:
          {{ if not .Values.externalNeo4j }}
            - name: NEO4J_HOST
              value: {{ include "plater.fullname" . }}-neo4j-service
            - name: NEO4J_HTTP_PORT
              value: "{{ .Values.app.neo4j.httpPort }}"
          {{ else }}
            - name: NEO4J_HOST
              value: {{ .Values.externalNeo4j.hostName }}
            - name: NEO4J_HTTP_PORT
              value: "{{ .Values.externalNeo4j.port }}"
          {{ end }}
          volumeMounts:
            - name: {{ include "plater.fullname" . }}-config-files
              mountPath: /check_neo.sh
              subPath: check_neo.sh
      containers:
        - name: {{ include "plater.fullname" . }}-web-container
          image: "{{ .Values.image.plater.repository }}:{{ .Values.image.plater.tag }}"
          imagePullPolicy: {{ .Values.image.plater.imagePullPolicy }}
          {{- with .Values.app.web.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "plater.fullname" . }}-env-configmap
          volumeMounts:
            - mountPath: /home/plater/Plater/PLATER/metadata
              name: {{ include "plater.fullname" . }}-metadata-pvc
              subPath: plater-metadata/
            - mountPath: /home/plater/Plater/PLATER/openapi-config.yaml
              name: {{ include "plater.fullname" . }}-config-files
              subPath: openapi-config.yaml
            - mountPath: /home/plater/Plater/skip_attr.json
              name: {{ include "plater.fullname" . }}-config-files
              subPath: skip-attr.json
      volumes:
        - name: {{ include "plater.fullname" . }}-config-files
          configMap:
            name: {{ include "plater.fullname" . }}-configmap
            defaultMode: 0777
        - name: {{ include "plater.fullname" . }}-metadata-pvc
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

