apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{- include "node-normalization-webserver.fullname" . }}-root-server"
  labels:
    {{- include "node-normalization-webserver.selectorLabels" . | nindent 4 }}
    service-type: "webserver"
    path: "root"
spec:
  selector:
    matchLabels:
      {{- include "node-normalization-webserver.selectorLabels" . | nindent 6 }}
      service-type: "webserver"
      path: "root"
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.redis_backend_config | toString | sha256sum  }}
      labels:
        {{- include "node-normalization-webserver.selectorLabels" . | nindent 8 }}
        service-type: "webserver"
        path: "root"
    spec:
      {{- with .Values.web.securityContext }}
      securityContext:
        {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: webserver-container
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.web.configPath }}
              name: "webserver-config"
              subPath: "redis_config.yaml"
          env:
            - name: "SERVER_ROOT"
              value: "{{ .Values.web.serverHostName }}"
            - name: "MATURITY_VALUE"
              value: "{{ .Values.x_trapi.maturity.value }}"
            - name: "LOCATION_VALUE"
              value: "{{ .Values.x_trapi.location.value }}"
          command:
            - 'gunicorn'
          args:
            - "-b"
            - "0.0.0.0:{{ .Values.web.port }}"
            - "-k"
            - "uvicorn.workers.UvicornWorker"
            {{ with .Values.web.extraArgs }}
              {{ . | toYaml | nindent 12 }}
            {{ end }}
            - 'node_normalizer.server:app'
          resources:
            {{ .Values.resources | toYaml | nindent 12 }}
          {{ if .Values.web.startupProbe.enabled }}
          startupProbe:
            httpGet:
             path: /docs
             port: {{ .Values.web.port }}
           {{ with .Values.web.startupProbe.config }}
            {{ . | toYaml | nindent 12 }}
           {{ end }}
          {{ end }}
          {{ if .Values.web.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /docs
              port: {{ .Values.web.port }}
           {{ with .Values.web.readinessProbe.config }}
            {{ . | toYaml | nindent 12 }}
           {{ end }}
          {{ end}}
          {{ if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /docs
              port: {{ .Values.web.port }}
           {{ with .Values.web.livenessProbe.config }}
            {{ . | toYaml | nindent 12 }}
           {{ end }}
          {{ end}}

      restartPolicy: Always
      volumes:
        - name: webserver-config
          configMap:
            name: "{{- include "node-normalization-webserver.fullname" . }}-webserver-config"
            defaultMode: 0777
