ingress:
  host: robokop.renci.org
  paths:
  - path: /api-docs(?:\/|$)(.*)
    pathType: Prefix
    backend:
      service:
        name: api-docs
        port:
          number: 8080
  - path: /question-builder(?:\/|$)(.*)
    pathType: Prefix
    backend:
      service:
        name: qgraph-svc
        port:
          number: 7080
  - path: /(.*)$
    pathType: Prefix
    backend:
      service:
        name: landing-page
        port:
          number: 3000

# qgraph .Values override
qgraph:
  env:
    robokache: http://qgraph-robokache
    strider: http://strider-web-service:5781
    aragorn: http://aragorn-aragorn-service:8080
    robokop_ara: http://aragorn-aragorn-robokop-service:8080
    node_normalizer: https://nodenormalization-sri.renci.org
    name_resolver: https://name-resolution-sri.renci.org
    biolink: https://raw.githubusercontent.com/biolink/biolink-model/v3.3.2/biolink-model.yaml

  qgraph:
    repository: ghcr.io/robokopu24/qgraph
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.1"
    service:
      type: ClusterIP
      port: 7080

  robokache:
    repository: ghcr.io/ncats-gamma/robokache
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v4.1.5"
    service:
      type: ClusterIP
      port: 8080
    dbPath: "/data"
