dataUrl: https://stars.renci.org/var/plater/bl-4.2.0/RobokopKG/d6841128f7cc5191/graph_d6841128f7cc5191.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-4.2.0/RobokopKG/d6841128f7cc5191/RobokopKG.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-4.2.0/RobokopKG/d6841128f7cc5191/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-4.2.0/RobokopKG/d6841128f7cc5191/testing_data.json