
id-id:
  auth:
    enabled: true
  master:
    persistence:
      size: 150Gi
    resources:
      limits:
        cpu: 1500m
        memory: 100Gi
      requests:
        cpu: 200m
        memory: 80Gi
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
    - "--save 300 1000000"
    - "--appendonly no"

  replica:
    replicaCount: 0

id-categories:
  auth:
    enabled: true
  master:
    persistence:
      size: 100Gi
    resources:
      limits:
        cpu: 1500m
        memory: 100Gi
      requests:
        cpu: 500m
        memory: 50Gi
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
    - "--save 300 1000000"
    - "--appendonly no"

  replica:
    replicaCount: 0

id-eq-id:
  auth:
    enabled: true
  master:
    persistence:
      size: 200Gi
    resources:
      limits:
        cpu: 3000m
        memory: 180Gi
      requests:
        cpu: 500m
        memory: 150Gi
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
    - "--save 300 1000000"
    - "--appendonly no"
  replica:
    replicaCount: 0

semantic-count:
  auth:
    enabled: true
  master:
    persistence:
      size: 20Mi
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 20Mi
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    resources:
      requests:
        memory: #
    extraFlags:
    - "--save 300 1000000"
    - "--appendonly no"
  replica:
    replicaCount: 0

conflation-db:
  auth:
    enabled: true
  master:
    persistence:
      size: 15Gi
    resources:
      limits:
        cpu: 1000m
        memory: 10Gi
      requests:
        cpu: 250m
        memory: 6Gi
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
    - "--save 300 1000000"
    - "--appendonly no"
  replica:
    replicaCount: 0

info-content:
  auth:
    enabled: true
  master:
    persistence:
      size: 500Mi
    resources:
      limits:
        cpu: 150m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 250Mi
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    resources:
      requests:
        memory: #
    extraFlags:
    - "--save 300 1000000"
    - "--appendonly no"
  replica:
    replicaCount: 0

chemical-drug-db:
  auth:
    enabled: true
  master:
    persistence:
      size: 300Mi
    resources:
      limits:
        cpu: 150m
        memory: 300Mi
      requests:
        cpu: 50m
        memory: 150Mi
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    resources:
      requests:
        memory: #
    extraFlags:
    - "--save 300 1000000"
    - "--appendonly no"
  replica:
    replicaCount: 0
