{{- if eq .Values.mode "restore" }}
{{- $fullName := include "node-normalization-loader.fullname" . -}}
{{- $codeDir := .Values.codeDir }}
{{- $dataDir := .Values.restore.dataDir }}
{{- $resources := .Values.resources }}
{{- $securityContext := .Values.securityContext }}
{{- $repository := .Values.restore.repository }}
{{- $tag := .Values.restore.tag }}
{{- $pullPolicy := .Values.restore.pullPolicy }}
{{- range $dbName, $dbConf := .Values.redis_backend_config }}
{{- $dbKubeName := $dbName | replace "_" "-"}}
{{- $dataStorageSize := $dbConf.storageSize }}
{{- range $index, $host := $dbConf.hosts }}
{{- $hostName := $host.host_name }}
{{- $port := $host.port }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $fullName }}-pipe-job-{{ $dbKubeName }}-{{ $index }}"
spec:
  template:
    metadata:
      name: "{{ $fullName }}-pipe-job-{{ $dbKubeName }}-{{ $index }}"
    spec:
      containers:
        - name: loader-container
          image: "{{ $repository }}:{{ $tag }}"
          imagePullPolicy: {{ $pullPolicy }}
          command:
            - /bin/bash
          args:
            - {{ $codeDir }}/run_pipe.sh
          volumeMounts:
            - mountPath:  {{ $codeDir }}/run_pipe.sh
              name: "loader-config"
              subPath: "run_pipe.sh"
            - mountPath: {{ $dataDir }}
              name: "data-dir"
          resources:
            {{ $resources | toYaml | nindent 12 }}
      restartPolicy: OnFailure
      {{ with $securityContext }}
      securityContext:
        {{ $securityContext | toYaml | nindent 8 }}
      {{ end }}
      volumes:
        - name: loader-config
          configMap:
            name: "{{ $fullName }}-{{ $dbKubeName }}-{{ $index }}-config"
            defaultMode: 0777
        - name: data-dir
          persistentVolumeClaim:
            claimName: "{{ $fullName }}-{{ $dbKubeName }}-{{ $index }}-loader-pvc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $fullName }}-{{ $dbKubeName }}-{{ $index }}-loader-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $dataStorageSize }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $fullName }}-{{ $dbKubeName }}-{{ $index }}-config"
data:
  run_pipe.sh: |-
    #!/bin/bash
    set -x

    # Eventually we should build a Docker image for this restore script, but during development this is good enough for now.
    apt-get update
    apt-get install -y wget python3 python3-pip

    # We have to handle pip separately.
    python3 -m venv "{{ $dataDir }}/venv"
    source "{{ $dataDir }}/venv/bin/activate"
    pip install rdbtools python-lzf

    # Download the archive file.
    wget -nv -O "{{ $dataDir }}/{{ $dbName }}.rdb.gz" "{{ $dbConf.restoreURL }}"

    # Unzip the archive file.
    gunzip "{{ $dataDir }}/{{ $dbName }}.rdb.gz"

    # Restore the file into the specified database.
    rdb -c protocol "{{ $dataDir }}/{{ $dbName }}.rdb" | pv > "{{ $dataDir }}/output.rdp"
    # | redis-cli -h {{ $hostName }} -p {{ $port }} --pipe

    # Report success.
    echo "Completed restoring {{ $dbConf.restoreURL }} into {{ $dbName }} at {{ $hostName }}:{{ $port }}."

    # Go into a sleep loop so we can examine this pod.
    while true; do sleep 5; done
---
{{ end }}
{{ end }}
{{- end }}