# Default values for filter-results-top-n
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeSelector: {}
affinity: {}
tolerations: []

image:
  repository: ghcr.io/ncatstranslator/workflow-runner:latest
  tag: latest

external_services:
  NORMALIZER_URL: ""
  SERVICES_MATURITY: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  host: ingress_HOST
  enabled: true
  class: ""
  pathType: "ImplementationSpecific"
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
  tls:
    enabled: false

app:
  port: 4321
  resources:
    requests:
      memory: 1000Mi
      cpu: 800m
    limits:
      memory: 1000Mi
      cpu: 800m

x_trapi:
  maturity:
    value: "maturity"
  location:
    value: "location"
