replicaCount: 1

image:
  repository: ghcr.io/robokopu24/api-docs
  tag: latest

# env:

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 8080
