replicaCount: 1

image:
  repository: ghcr.io/robokopu24/api-docs
  tag: 2.2.1

# env:

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 8080

# Check for override in parent chart
ingress:
  host: test-rkfe.apps.renci.org
  path: /api-docs(?:\/|$)(.*)
  public: false