apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "answer-coalesce-test.fullname" . }}-redis-config
data:
  config.json: |-
    {
    "redis_host": "{{ include "answer-coalesce-test.fullname" . }}-redis-service",
    "redis_port": {{ .Values.redis.service.port }},
    "redis_password": "",
    "test_mode": 0
    }
  seed_db.sh: |-
    #!/bin/sh
    set -x
    FILE=/data/dump.rdb
    wget -nv -O $FILE {{ .Values.dataUrl }}