# Default values for information-radiator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ubuntu
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "22.04"

informationradiator:
  storage: 20Gi

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  path: "/"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "250m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      keepalive_timeout 86400;
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/send-timeout: "86400"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "86400"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # kubernetes.io/tls-acme: "true"
  host: informationradiator.apps.renci.org
  pathType: ImplementationSpecific
  tls:
    enabled: false
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nginx:
  tag: 1.17
  service:
    type: ClusterIP
    port: 80

reporting_ui:
  tag: 1.27.0
  service:
    type: ClusterIP
    port: 80

reporting_service:
  tag: 1.28.0
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 400m
      memory: 400M

iam_service:
  tag: 1.15.0
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 400m
      memory: 400M

iam_db_service:
  # postgres
  service:
    type: ClusterIP
    port: 5432

logstash:
  tag: 7.16.3
  service:
    type: ClusterIP
    port_1: 5044
    port_2: 9600
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 800m
      memory: 800M

minio:
  tag: RELEASE.2020-06-03T22-13-49Z
  service:
    type: ClusterIP
    port: 9000
  access_key: changeit
  secret_key: changeit

artifacts:
  tag: 1.8.0
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 400m
      memory: 400M

redis:
  tag: 5.0.5
  password: changeit
  service:
    type: ClusterIP
    port: 6379

elasticsearch:
  tag: 7.16.3
  service:
    type: ClusterIP
    port_1: 9200
    port_2: 9300
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 800m
      memory: 800M

rabbitmq:
  tag: 3.8-management
  service:
    type: ClusterIP
    web_port: 15672
    amqp_port: 5672
  password: changeit
  user: changeit
  erl_args: changeit
  storage:
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 400m
      memory: 400M

postgres:
  tag: 9.6
  service:
    type: ClusterIP
    port: 5432
  password: changeit
  user: changeit

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
