apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "answer-appraiser.fullname" . }}-logs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.appraiser.logsPVCSize }}
