apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ac-loader.fullname" . }}-configmap
  labels:
    {{- include "ac-loader.labels" . | nindent 4 }}
data:
  download.sh: |-
    #!/bin/sh
    cd /data
    {{- range .Values.dataFiles }}
    wget {{ .  }}
    {{- end }}