apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-type: elasticsearch
  name: {{ include "information-radiator.fullname" . }}-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      service-type: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service-type: elasticsearch
    spec:
      containers:
        - name: {{ include "information-radiator.fullname" . }}-elasticsearch
          image: 'elasticsearch:{{ .Values.elasticsearch.tag }}'
          env:
            - name: ES_JAVA_OPTS
              value: -Xmx1024m -Xms512m
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
            - name: bootstrap.memory_lock
              value: "true"
          {{ if .Values.resources }}
          resources: {{ toYaml .Values.elasticsearch.resources | nindent 12 }}
          {{ end }}
          volumeMounts:
            - mountPath: "/usr/share/elasticsearch/config/elasticsearch.yml"
              name: "elasticsearch-config"
              subPath: "elasticsearch.yml"
      restartPolicy: Always
      volumes:
        - name: elasticsearch-config
          configMap:
            name: {{ include "information-radiator.fullname" . }}-elasticsearch-configmap
            defaultMode: 0777
status: {}
