apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-type: {{ include "information-radiator.fullname" . }}-elasticsearch
  name: {{ include "information-radiator.fullname" . }}-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      service-type: {{ include "information-radiator.fullname" . }}-elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service-type: {{ include "information-radiator.fullname" . }}-elasticsearch
    spec:
      containers:
        - name: {{ include "information-radiator.fullname" . }}-elasticsearch
          image: 'elasticsearch:latest'
          env:
            - name: ES_JAVA_OPTS
              value: -Xmx1024m -Xms512m
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
            - name: bootstrap.memory_lock
              value: "true"
          resources: {}
          volumeMounts:
            - mountPath: "/usr/share/elasticsearch/config"
              name: "elasticsearch-config"
              subPath: "elasticsearch.yaml"
      restartPolicy: Always
      volumes:
        - name: elasticsearch-config
          configMap:
            name: {{ include "information-radiator.fullname" . }}-elasticsearch-configmap
            defaultMode: 0777
status: {}
