apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "information-radiator.fullname" . }}-iam-db-configmap
data:
  iam-db-init.sh: |-
    #!/bin/bash
    if [[ $(psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER -tAc "SELECT 1 FROM pg_namespace WHERE nspname = 'zafira'") == '1' ]]; then
      echo "Schema already exists"
      exit 1
    fi
    psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER -f /docker-entrypoint-initdb.d/sql/db-iam-database.sql
  db-iam-database.sql: |-
    CREATE SCHEMA IF NOT EXISTS zafira;
