apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-type: iam-service
  name: {{ include "information-radiator.fullname" . }}-iam-service
spec:
  selector:
    matchLabels:
      service-type: iam-service
  template:
    metadata:
      labels:
        service-type: iam-service
    spec:
      containers:
        - image: 'zebrunner/iam-service:{{ .Values.iam_service.tag }}'
          name: {{ include "information-radiator.fullname" . }}-iam-service
          envFrom:
          - configMapRef:
              name: {{ include "information-radiator.fullname" . }}-iam-configmap
          {{ if .Values.resources }}
          resources: {{ toYaml .Values.iam_service.resources | nindent 12 }}
          {{ end }}
      restartPolicy: Always
