apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-type: {{ include "information-radiator.fullname" . }}-logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      service-type: {{ include "information-radiator.fullname" . }}-logstash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service-type: {{ include "information-radiator.fullname" . }}-logstash
    spec:
      containers:
        - env:
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
          image: 'logstash:{{ .Values.logstash.tag }}'
          name: logstash
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: logstash-config
              subPath: logstash.conf
            - mountPath: /mapping.json
              name: logstash-config
              subPath: mapping.json
            - mountPath: /test-run-data-template.json
              name: logstash-config
              subPath: test-run-data-template.json
      restartPolicy: Always
      volumes:
        - name: logstash-config
          configMap:
            name: {{ include "information-radiator.fullname" . }}-logstash-configmap
            defaultMode: 0777
status: {}
