apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-type: minio-storage
  name: {{ include "information-radiator.fullname" . }}-minio-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      service-type: minio-storage
  template:
    metadata:
      labels:
        service-type: minio-storage
    spec:
      containers:
        - name: {{ include "information-radiator.fullname" . }}-minio-storage
          image: 'minio/minio:{{ .Values.minio.tag }}'
          env:
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.access_key }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.minio.secret_key }}
          {{ if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{ end }}
          command:
            - "server"
          args:
            - "/data"
      restartPolicy: Always
