apiVersion: v1
kind: Service
metadata:
  labels:
    service-type: nginx
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service-type: nginx
status:
  loadBalancer: {}
