apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-type: {{ include "information-radiator.fullname" . }}-postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service-type: {{ include "information-radiator.fullname" . }}-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service-type: {{ include "information-radiator.fullname" . }}-postgres
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=200
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
          image: 'qaprosoft/postgres:latest'
          name: postgres
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata-volume
            - mountPath: "/docker-entrypoint-initdb.d"
              name: "postgres-config"
      restartPolicy: Always
      volumes:
        - name: postgres-config
          configMap:
            name: {{ include "information-radiator.fullname" . }}-postgres-configmap
            defaultMode: 0777
status: {}
