apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-type: proxy
  name: {{ include "information-radiator.fullname" . }}-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service-type: proxy
  template:
    metadata:
      labels:
        service-type: proxy
    spec:
      containers:
        - name: {{ include "information-radiator.fullname" . }}-proxy
          image: 'nginx:{{ .Values.nginx.tag }}'
          ports:
            - containerPort: 80
              protocol: TCP
          {{ if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{ end }}
          volumeMounts:
            - mountPath: "/etc/nginx/nginx.conf"
              name: "nginx-config"
              subPath: "nginx.conf"
            - mountPath: "/etc/nginx/ssl/ssl.crt"
              name: "nginx-config"
              subPath: "ssl.crt"
            - mountPath: "/etc/nginx/ssl/ssl.key"
              name: "nginx-config"
              subPath: "ssl.key"
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "information-radiator.fullname" . }}-nginx-configmap
            defaultMode: 0777
      restartPolicy: Always
status: {}
