apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "information-radiator.fullname" . }}-reporting-ui-configmap
data:
  SERVER_URL: http://{{ include "information-radiator.fullname" . }}-proxy:80/reporting-service
