apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-type: {{ include "information-radiator.fullname" . }}-ui
  name: {{ include "information-radiator.fullname" . }}-reporting-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      service-type: {{ include "information-radiator.fullname" . }}-ui
  template:
    metadata:
      labels:
        service-type: {{ include "information-radiator.fullname" . }}-ui
    spec:
      containers:
        - env:
            - name: SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: SERVER_URL
                  name: configmap
          image: 'zebrunner/reporting-ui:{{ .Values.ui.tag }}'
          name: {{ include "information-radiator.fullname" . }}-reporting-ui
          resources: {}
      restartPolicy: Always
status: {}
