apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-type: {{ include "information-radiator.fullname" . }}-reporting-service
  name: {{ include "information-radiator.fullname" . }}-reporting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service-type: {{ include "information-radiator.fullname" . }}-reporting-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service-type: {{ include "information-radiator.fullname" . }}-reporting-service
    spec:
      containers:
        - name: {{ include "information-radiator.fullname" . }}-reporting-service
          image: 'zebrunner/reporting-service:latest'
          envFrom:
            - configMapRef:
              name: {{ include "information-radiator.fullname" . }}-configmap
          resources: {}
      restartPolicy: Always
status: {}
