apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "yobokop.fullname" . }}-robokache
  labels:
    {{- include "yobokop.labels" . | nindent 4 }}
    service-type: database
spec:
  serviceName: {{ include "yobokop.fullname" . }}-robokache
  selector:
    matchLabels:
      {{- include "yobokop.selectorLabels" . | nindent 6 }}
      service-type: database
  template:
    metadata:
      labels:
        {{- include "yobokop.selectorLabels" . | nindent 8 }}
        service-type: database
    spec:
      containers:
        - name: {{ .Chart.Name }}-robokache-container
          image: "{{ .Values.robokache.repository }}:{{ .Values.robokache.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.robokache.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.robokache.dbPath }}
              name: {{ include "yobokop.fullname" . }}-robokache-data-volume
              subPath: data
          resources:
            {{ toYaml .Values.robokache.resources | nindent 12 }}

  volumeClaimTemplates:
    - metadata:
        name: {{ include "yobokop.fullname" . }}-robokache-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.robokache.storage.size }}
