dataUrl: https://stars.renci.org/var/plater/bl-3.5.4/CAMKP_Automat/ded8cfcdee598475/graph_ded8cfcdee598475.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-3.5.4/CAMKP_Automat/ded8cfcdee598475/CAMKP_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-3.5.4/CAMKP_Automat/ded8cfcdee598475/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-3.5.4/CAMKP_Automat/ded8cfcdee598475/testing_data.json