# Default values for name-lookup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



webServer:
  replicaCount: 1
  service:
    port: 2433
    type: ClusterIP
  # container port
  port: 2433
  image:
    repository: ghcr.io/translatorsri/nameresolution
    tag: v1.2.0

dataUrl: "https://stars.renci.org/var/babel_outputs/2023apr24/solr/snapshot.backup.tar.gz"
forceRun: false

busybox:
  image:
    repository: busybox
    tag: "1.35"

# busybox:
#   image:
#     repository: busybox
#     tag: latest

solr:
  service:
    port: 8983
    type: ClusterIP
  # container port
  port: 8983
  heap_mem: "-Xms58G -Xmx58G"
  image:
    repository: solr
    tag: 9.1
  resources:
    requests:
      memory: "64Gi"
    limits:
      memory: "64Gi"
  # As of Babel 2023jul13, we need 130G to store the
  # uncompressed backup + 131G Solr database
  # So 300Gi should be enough for the time being.
  storage: 300Gi

  initresources:
    requests:
      memory: 32Gi
      cpu: 1000m
    limits:
      memory: 64Gi
      cpu: 1000m

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  pathType: "ImplementationSpecific"
  host:
  class:

x_trapi:
  maturity:
    value: "maturity"
  location:
    value: "location"
