# Default values for name-lookup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



webServer:
  replicaCount: 1
  service:
    port: 2433
    type: ClusterIP
  # container port
  port: 2433
  image:
    repository: ghcr.io/translatorsri/nameresolution
    tag: "v1.2.0"

dataUrl: "https://stars.renci.org/var/babel_outputs/2022dec2-2/solr/snapshot.backup.tar.gz"
forceRun: false

busybox:
  image:
    repository: busybox
    tag: "1.35"

# busybox:
#   image:
#     repository: busybox
#     tag: latest

solr:
  service:
    port: 8983
    type: ClusterIP
  # container port
  port: 8983
  heap_mem: "-Xms4000m -Xmx4000m"
  image:
    repository: solr
    tag: latest
  resources:
    requests:
      memory: "5Gi"
    limits:
      memory: "5Gi"

  initresources:
    requests:
      memory: 5Gi
      cpu: 1000m
    limits:
      memory: 10Gi
      cpu: 1000m

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  pathType: "ImplementationSpecific"
  host:
  class:

x_trapi:
  maturity:
    value: "maturity"
  location:
    value: "location"
