# Default values for name-lookup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



webServer:
  replicaCount: 1
  service:
    port: 2433
    type: ClusterIP
  # container port
  port: 2433
  image:
    repository: ghcr.io/translatorsri/nameresolution
    tag: v1.3.4

dataUrl: "https://stars.renci.org/var/babel_outputs/2023jul13/solr/snapshot.backup.tar.gz"
forceRun: false

busybox:
  image:
    repository: busybox
    tag: "1.35"

# busybox:
#   image:
#     repository: busybox
#     tag: latest

solr:
  service:
    port: 8983
    type: ClusterIP
  # container port
  port: 8983
  heap_mem: "-Xms180G -Xmx180G"
  gc: "-XX:NewSize=4G -XX:MaxNewSize=4G -XX:+UseG1GC -XX:MaxGCPauseMillis=1000 -XX:+UnlockExperimentalVMOptions -XX:G1MaxNewSizePercent=40 -XX:G1NewSizePercent=5 -XX:G1HeapRegionSize=32M -XX:InitiatingHeapOccupancyPercent=90"
  image:
    repository: solr
    tag: "9.1"
  resources:
    requests:
      memory: "300Gi"
      cpu: 1000m
    limits:
      memory: "64Gi"
      memory: "300Gi"
      cpu: 2000m
  # As of Babel 2023may18, we need 128G to store the
  # backup + uncompressed backup + Solr database
  # So 500Gi should be enough for the time being.
  storage: 500Gi

  initresources:
    requests:
      memory: 32Gi
      cpu: 1000m
    limits:
      memory: 64Gi
      cpu: 1000m

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  pathType: "ImplementationSpecific"
  host:
  class:

x_trapi:
  maturity:
    value: "maturity"
  location:
    value: "location"
