apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aragorn-ranker.fullname" . }}
  labels:
    app: {{ include "aragorn-ranker.name" . }}
    trapi: "1.4"
spec:
  selector:
    matchLabels:
      app: {{ include "aragorn-ranker.name" . }}
      trapi: "1.4"
  template:
    metadata:
      labels:
        app: {{ include "aragorn-ranker.name" . }}
        trapi: "1.4"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-config-map.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/gunicorn-config-map.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-web-container
          command:
            - 'gunicorn'
          args:
            - "-b"
            - "0.0.0.0:{{ .Values.app.port}}"
            - "-w"
            - "4"
            - "-k"
            - "ranker.uvicorn_custom.SubPathWorker"
            - "--timeout"
            - "{{ .Values.app.workerTimeout }}"
            - 'ranker.server:APP'
          envFrom:
            - configMapRef:
                name: {{ include "aragorn-ranker.fullname" . }}-configmap
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.app.port }}
            name: http
            protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /repo/aragorn-ranker/ranker/uvicorn_custom.py
            name: {{ include "aragorn-ranker.fullname" . }}-gunicorn-conf
            subPath: uvicorn_custom.py
          env:
          - name: CACHE_PASSWORD
            {{- if .Values.omnicorpRedisGraph.auth.password }}
            value: {{ .Values.omnicorpRedisGraph.auth.password }}
            {{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.omnicorpRedisGraph.auth.secret }}
                key: {{ .Values.omnicorpRedisGraph.auth.secretPasswordKey }}
            {{- end }}
      volumes:
      - name: {{ include "aragorn-ranker.fullname" . }}-gunicorn-conf
        configMap:
          name: {{ include "aragorn-ranker.fullname" . }}-gunicorn-conf
          defaultMode: 0777
      restartPolicy: Always
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
