{{- if and .Values.ingress.class (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.strider.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.strider.annotations "kubernetes.io/ingress.class" .Values.ingress.class }}
  {{- end }}
  {{- if not (hasKey .Values.ingress.kpRegistry.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.kpRegistry.annotations "kubernetes.io/ingress.class" .Values.ingress.class }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "strider.fullname" . }}-ingress
  {{- with .Values.ingress.strider.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  {{- if and .Values.ingress.class (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ .Values.ingress.strider.host | quote }}
    secretName: {{ .Values.ingress.strider.host }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.ingress.strider.host }}
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          pathType: "{{ .Values.ingress.pathType }}"
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ include "strider.fullname" . }}-web-service
              port:
                number: {{ .Values.strider.service.port }}
            {{- else }}
            serviceName: {{ include "strider.fullname" . }}-web-service
            servicePort: {{ .Values.strider.service.port }}
            {{- end }}
        {{- if .Values.redisinsight.enabled }}
        - path: "/redis-insight(/|$)(.*)"
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          pathType: "{{ .Values.ingress.pathType }}"
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ include "strider.fullname" . }}-redisinsight
              port:
                number: 80
            {{- else }}
            serviceName: {{ include "strider.fullname" . }}-redisinsight
            servicePort: 80
            {{- end }}
        {{- end }}
