# Default values for node-normalization-loader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# There are two node-normalization-loader modes:
# 1. `load` (default): Use the loader to load a set of backend Redis servers with Babel compendium/conflation JSONL files.
# 2. `restore`: Use the loader-pipe-job to load the database backups into the backend Redis databases.
mode: load

image:
  repository: "ghcr.io/translatorsri/nodenormalization"
  tag: "chem_conflate"
  pullPolicy: Always
fullnameOverride: ""

# Settings to use for a restore job.
restore:
  repository: "redis"
  tag: "7-alpine"
  pullPolicy: Always
  dataDir: "/data"
  dataSize: 50G

data:
  compendia:
    storageSize: 10G
    sourceBaseUrl: "https://stars.renci.org/var/babel_outputs/2023aug3-with-drugs/compendia/"
    files:
  conflations:
    storageSize: 1G
    sourceBaseUrl: "https://stars.renci.org/var/babel_outputs/2023aug3-with-drugs/conflation/"
    configs:
      - file: "DrugChemical.txt"
        types:
          - biolink:ChemicalEntity
          - biolink:Drug
        redis_db: "chemical_drug_db"
codeDir: /code

redis_backend_config: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  fsGroupChangePolicy: "Always"

resources:
  limits:
    memory: 10Gi
    ephemeral-storage: 2Gi
  requests:
    memory: 10Gi
    ephemeral-storage: 2Gi
