# Default values for strider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

strider:
  strategy: Recreate
  replicaCount: 1
  logsPVCSize: 3Gi
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  image:
    tag: latest
    repository: ghcr.io/ranking-agent/strider
    imagePullPolicy: Always
  service:
    type: ClusterIP
    port: 5781
  container:
    port: 5781
  uvicornWorkerCount: 6
  updateCronInterval: "0 */6 * * *"
  workerTimeout: 400

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 40

  resources:
    requests:
      memory: 16Gi
      cpu: 1000m
    limits:
      memory: 20Gi
      cpu: 3000m

# liveliness prob values
probes:
  strider:
    enabled: false
    failureThreshold: 5
    successThreshold: 1
    period: 120
    timeoutSeconds: 10

redis:
  image:
    tag: latest
    repository: redis
  dbPath: /data
  service:
    port: 6379
    type: ClusterIP
  resources:
    limits:
      memory: 10Gi
    requests:
      memory: 10Gi
  args:
    - --maxmemory
    - '10gb'
    - --maxmemory-policy
    - 'volatile-lfu'
    - --loglevel
    - 'notice'
    - --logfile
    - '/data/strider_cache.log'
    - --stop-writes-on-bgsave-error
    - 'no'
    - --dbfilename
    - 'strider_cache.rdb'
    - --proto-max-bulk-len
    - '1000mb'
    - --activedefrag
    - 'yes'
    - --timeout
    - '60'
  nodeSelector: {}
  affinity: {}
  tolerations: []  

ingress:
  enabled: false
  class: ""
  pathType: "ImplementationSpecific"
  path: "/"
  strider:
    host: "the strider host name"
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "250m"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        keepalive_timeout 86400;
      nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
      nginx.ingress.kubernetes.io/send-timeout: "86400"
      nginx.ingress.kubernetes.io/service-upstream: "true"
      nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "86400"
      # nginx.ingress.kubernetes.io/rewrite-target: /$2

env:
  max_process_time: 3400
  redis_expiration: 604800
  redis_host: strider-redis-service
  jaeger_enabled: "False"
  jaeger_host: jaeger-otel-agent
  service_name: "STRIDER"
  jaeger_port: 6831
  kp_trapi_version: "1.5.0"
  kp_timeout: 10
  information_content_threshold: 75

x_trapi:
  maturity:
    value: "maturity"
  location:
    value: "location"

redisinsight:
  enabled: false

app:
  nodeSelector: {}
  affinity: {}
  tolerations: []

